### ISSUE TITLE
documentation for a is misleading

### ISSUE THREAD

**Issue by stephens999** [stephenslab/EbayesThresh#1]
a is referred to as a "scale parameter" but actually it is a rate parameter! (inverse scale)

**Comment by pcarbo** [comment]
@stephens999 I agree. From the [Wikipedia page](https://en.wikipedia.org/wiki/Laplace_distribution), `1/a` is the scale parameter. I will correct this.

**Comment by pcarbo** [comment]
@stephens999 I think I have mostly fixed this. The only point of confusion is the `zetafromx` function, which takes an additional vector of "scale factors". From the code, it looks like they may be standard deviations, but hard to say for sure. Do you have any idea what this is?

**Comment by stephens999** [comment]
I don't know.
(That function doesn't seem to be used anywhere!)

Matthew

On Tue, Dec 12, 2017 at 12:40 PM, Peter Carbonetto <notifications@github.com
