### ISSUE TITLE
limits of optimization could be improved

### ISSUE THREAD

**Issue by stephens999** [stephenslab/EbayesThresh#2]
currently the optimization is over a in (0.04 to 3). This is not 
very adaptive to the scale of the data!  It would be good to scale these
according to the data.

**Comment by pcarbo** [comment]
@stephens999 In the comments in `wandafromx.R`, it says:

> If `universalthresh=TRUE`, the thresholds will be upper bounded by universal threshold adjusted by standard deviation. The threshold is constrained to lie between 0 and `sqrt(2log(n))*s`.

My understanding is that the inverse scale parameter is additionally constrained to lie between 0.04 and 3, and you would like this constraint to also adapt to the scale of the data. Is this correct?

**Comment by stephens999** [comment]
correct. I have implemented something and will push soon.

On Tue, Dec 12, 2017 at 12:48 PM, Peter Carbonetto <notifications@github.com

**Comment by stephens999** [comment]
addressed by a434fc92e1ee9bf7cb479ae065a2e2e1d763abb6
